[tool.poetry]
name = "popcat-api"
version = "0.0.1"
description = "An async API wrapper around popcat"
authors = ["Infernum1"]
repository = 
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = "^3.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
